config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'ask', to: 'questions#ask', as: :question_ask
get 'answer', to: 'questions#answer', as: :question_answer

post 'answer', to: 'questions#answer', as: :question_meth

root to: 'questions#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def home
	end

	def ask
	end

	def answer
		@question = params[:question]

		if @question == "I am going to work"
			@answer = "Great !"
		elsif @question.include?("?")
			@answer = "Silly question, get dressed and go to work!"
		else 
			@answer = "I don't care, get dressed and go to work!"
		end
	end

	def create

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
	   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">
      <h1>Stupid Coaching</h1>
    </div>

    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="container display">
	<div class="row">
		<div class="col-sm-4">
			<p id="question"><%= @question %>
				<br/><em>-You</em>
			</p>
			<p id="answer"><strong><%= @answer %></strong>
				<br/><em>-Your coach</em>
			</p>
		</div>
	</div>
</div>

<div class="container">
	<button type="button" class="btn btn-outline-primary link"><%= link_to "ask new question", question_ask_path %></button>
</div>

app/views/questions/ask.html.erb
<div class="container text-center">
	<form action="answer" method="post">
	<%= hidden_field_tag :authenticity_token,form_authenticity_token %>
	  <div class="form-group">
	    <input type="text" class="form-control" name="question"placeholder="Enter a question">
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>

app/views/questions/home.html.erb
<div class="container text-center">
	<button type="button" class="btn btn-outline-primary"><%= link_to "ask new question", question_ask_path %></button>
</div>